name       : leveldb
version    : 1.19
release    : 2
source     :
    - https://github.com/google/leveldb/archive/v1.19.tar.gz : 7d7a14ae825e66aabeb156c1c3fae9f9a76d640ef6b40ede74cc73da937e5202
license    : BSD-3-Clause
component  : programming
optimize   : speed
summary    : Fast key-value storage library
description: |
    LevelDB is a fast key-value storage library written at Google that provides an ordered mapping from string keys to string values.
patterns   :
    - devel : /usr/bin/db_bench
builddeps  :
    - pkgconfig(snappy)
setup      : |
    %patch -p1 < $pkgfiles/Use-Solus-flags.patch
build      : |
    export CXXFLAGS=${CXXFLAGS/-flto/}
    %make
install    : |
    install -dm 00755 $installdir/usr/include/leveldb
    install -dm 00755 $installdir/usr/lib64
    install -dm 00755 $installdir/usr/bin

    install -Dm 00644 include/leveldb/* $installdir/usr/include/leveldb
    install -Dm 00644 out-shared/libleveldb* $installdir/usr/lib64
    install -Dm 00755 out-static/db_bench $installdir/usr/bin/db_bench
check      : |
    %make check
