name       : leveldb
version    : 1.19
release    : 1
source     :
    - https://github.com/google/leveldb/archive/v1.19.tar.gz : 7d7a14ae825e66aabeb156c1c3fae9f9a76d640ef6b40ede74cc73da937e5202
license    : BSD-3-Clause
component  : programming
summary    : Fast key-value storage library
description: |
    LevelDB is a fast key-value storage library written at Google that provides an ordered mapping from string keys to string values.
build      : |
    %make
install    : |
    install -dm 00755 $installdir/usr/include/leveldb
    install -dm 00755 $installdir/usr/lib64

    install -m 00644 include/leveldb/* $installdir/usr/include/leveldb
    install -m 00644 out-shared/libleveldb* $installdir/usr/lib64
