name       : leveldb
version    : 1.20
release    : 3
source     :
    - https://github.com/google/leveldb/archive/v1.20.tar.gz : f5abe8b5b209c2f36560b75f32ce61412f39a2922f7045ae764a2c23335b6664
license    : BSD-3-Clause
component  : programming
optimize   : speed
summary    : Fast key-value storage library
description: |
    LevelDB is a fast key-value storage library written at Google that provides an ordered mapping from string keys to string values.
patterns   :
    - devel : /usr/bin/db_bench
builddeps  :
    - snappy-devel
setup      : |
    %patch -p1 < $pkgfiles/Use-Solus-flags.patch
build      : |
    export CXXFLAGS=${CXXFLAGS/-flto/}
    %make
install    : |
    install -dm 00755 $installdir/usr/include/leveldb
    install -dm 00755 $installdir/usr/lib64
    install -dm 00755 $installdir/usr/bin

    install -Dm 00644 include/leveldb/* $installdir/usr/include/leveldb
    install -Dm 00644 out-shared/libleveldb* $installdir/usr/lib64
    install -Dm 00755 out-static/db_bench $installdir/usr/bin/db_bench
check      : |
    %make check
